website/custom/urls.py
from django.urls import path

from custom import views

app_name = "custom"

urlpatterns = [
    path("i-love-you/", views.ILoveYou.as_view(), name="i_love_you"),
    path("love/", views.Cube3D.as_view(), name="love"),
    path("happy-new-year/", views.NewYear.as_view(), name="happy-new-year"),
    path("scrollbar/", views.ScrollbarGallery.as_view(), name="scrollbar_pagination"),
]

website/huutuananh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import include, path


def trigger_error(request):
    """Kiểm tra thử thiết lập của Sentry"""
    result = 1 / 0
    return (result, request)


def healthcheck(request):
    "Healthcheck"
    return HttpResponse("HEALTHCHECK/", content_type="text/plain", status=200)


urlpatterns = [
    # Kiểm tra thiết lập Sentry
    path("sentry-debug/", trigger_error),
    # Đường dẫn của ứng dụng bên thứ 3
    path("summernote/", include("django_summernote.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    # Đường dẫn của all_auth
    path("logout", LogoutView.as_view()),
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

if settings.DEBUG:
    urlpatterns += [
        path("admin/", admin.site.urls),
    ]
else:
    urlpatterns += [
        path("custom-admin-url", admin.site.urls),
    ]

if not settings.IS_INSTALLING:
    urlpatterns += [
        # Đường dẫn của ứng dụng cá nhân
        path("weddings/", include("weddings.urls")),
        path("custom/", include("custom.urls")),
    ]

website/weddings/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from weddings.views import (
    ViewGlanzGolden,
    ViewGuiLoiChuc,
    ViewMyWedding,
    ViewTatCaLoiChuc,
    ViewTrueLove,
    ViewTrueLoveComingSoon,
    ViewTrueLoveCustom,
    ViewTrueLoveInvitation,
    ViewCountDays,
)

app_name = "weddings"

urlpatterns = [
    path("my-wedding/", ViewMyWedding.as_view(), name="my_wedding"),
    path("true-love/", ViewTrueLove.as_view(), name="true_love"),
    path(
        "true-love/<slug:slug>", ViewTrueLoveCustom.as_view(), name="true_love_custom"
    ),
    path(
        "true-love/invitation/<uuid:uid>",
        ViewTrueLoveInvitation.as_view(),
        name="true_love_invitation",
    ),
    path(
        "true-love/coming-soon/", ViewTrueLoveComingSoon.as_view(), name="coming_soon"
    ),
    path("glanz/golden", ViewGlanzGolden.as_view(), name="true_love"),
    path("love-story/", ViewCountDays.as_view(), name="love_story"),
    path("gui_loi_chuc/", ViewGuiLoiChuc.as_view(), name="gui_loi_chuc"),
    path(
        "true-love/nhung-loi-chuc/<int:pk_id>",
        cache_page(60 * 5)(ViewTatCaLoiChuc.as_view()),
        name="nhung_loi_chuc",
    ),
]

website/weddings/forms.py
from django import forms
from weddings.models import Wish


class FormWish(forms.ModelForm):
    # Form liên hệ trong trang chủ
    class Meta:
        model = Wish
        fields = [
            "name",
            "phone",
            "email",
            "facebook",
            "message",
            "wedding",
        ]
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "id": "name",
                    "class": "form-control",
                    "placeholder": "Tên của bạn (Bắt buộc)",
                }
            ),
            "phone": forms.TextInput(
                attrs={
                    "id": "phone",
                    "class": "form-control",
                    "placeholder": "Số điện thoại (Bắt buộc)",
                }
            ),
            "email": forms.EmailInput(
                attrs={
                    "id": "email",
                    "class": "form-control",
                    "placeholder": "Email (Không bắt buộc)",
                    "required": False,
                }
            ),
            "facebook": forms.TextInput(
                attrs={
                    "id": "facebook",
                    "class": "form-control",
                    "placeholder": "Link Facebook (Không bắt buộc)",
                    "required": False,
                }
            ),
            "message": forms.Textarea(
                attrs={
                    "id": "message",
                    "placeholder": "Lời nhắn gửi đến đôi tình nhân",
                }
            ),
            "wedding": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "id": "wedding",
                    "style": "display: None",
                }
            ),
        }

website/weddings/views.py
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.middleware.csrf import get_token
from django.views import View
from django.views.generic import TemplateView
from weddings.forms import FormWish
from weddings.models import (
    ImportantDay,
    LoveStory,
    Person,
    Photo,
    Wedding,
    Wish,
    Invitation,
)
from datetime import datetime


# Create your views here.
class ViewMyWedding(TemplateView):
    """Giao diện My wedding
    http://kamleshyadav.com/html/wedding/?storefront=envato-elements
    """

    template_name = "my_wedding/my_wedding.html"


class ViewTrueLove(TemplateView):
    """Giao diện True love
    https://html.themexriver.com/true-love/?storefront=envato-elements#main
    """

    template_name = "true_love/true_love.html"


class ViewTrueLoveCustom(TemplateView):
    """Giao diện True love
    https://html.themexriver.com/true-love/?storefront=envato-elements#main
    """

    template_name = "true_love/true_love_custom.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if slug := kwargs.get("slug"):
            if wedding := list(
                Wedding.objects.select_related(
                    "chu_re__donate_box", "co_dau__donate_box"
                ).filter(slug=slug)
            ):
                self._lay_thong_tin_wedding(wedding, context)
        return context

    def _lay_thong_tin_wedding(self, wedding, context):
        wedding_info = wedding[0]
        og_url = self.request.build_absolute_uri(
            reverse("weddings:true_love_custom", kwargs={"slug": wedding_info.slug})
        )
        og_image_url = self.request.build_absolute_uri(wedding_info.preview_image.url)
        love_stories = LoveStory.objects.filter(wedding=wedding_info).order_by(
            "ngay_ky_niem"
        )
        events = ImportantDay.objects.filter(wedding=wedding_info).order_by(
            "ngay_dien_ra"
        )
        photos = (
            Photo.objects.filter(wedding=wedding_info)
            .prefetch_related("phan_loai")
            .order_by("id")
        )
        families = Person.objects.filter(
            relationship__code="BM",
            nguoi_lien_quan__in=[wedding_info.chu_re, wedding_info.co_dau],
        )

        context["wedding_info"] = wedding_info
        context["og_url"] = og_url
        context["og_image_url"] = og_image_url
        context["love_stories"] = list(love_stories)
        context["events"] = list(events)
        context["slide_photos"] = []
        context["gallery"] = []
        context["wish_form"] = FormWish()
        context["wish_form"].fields["wedding"].widget.attrs.update(
            {
                "value": wedding_info.id,
            }
        )
        # context["wishes"] = wishes

        for photo in photos:
            if photo.is_slide:
                context["slide_photos"].append(photo)
            else:
                context["gallery"].append(photo)

        context["photo_filter"] = {
            (phan_loai.code, phan_loai.ten)
            for photo in photos
            for phan_loai in photo.phan_loai.all()
            if photo.phan_loai.all()
        }
        if families:
            context["families"] = {
                "ong_noi": families.get(
                    nguoi_lien_quan=wedding_info.chu_re, gioi_tinh="NAM"
                ),
                "ba_noi": families.get(
                    nguoi_lien_quan=wedding_info.chu_re, gioi_tinh="NU"
                ),
                "ong_ngoai": families.get(
                    nguoi_lien_quan=wedding_info.co_dau, gioi_tinh="NAM"
                ),
                "ba_ngoai": families.get(
                    nguoi_lien_quan=wedding_info.co_dau, gioi_tinh="NU"
                ),
            }


class ViewTrueLoveComingSoon(TemplateView):
    """Giao diện True love - Coming soon
    https://html.themexriver.com/true-love/?storefront=envato-elements#main
    """

    template_name = "true_love/coming-soon.html"


class ViewGlanzGolden(TemplateView):
    """Giao diện Glanz Golden
    http://glanz.starkethemes.com/html/01_03_home_golden.html
    """

    template_name = "glanz/golden/golden.html"


class ViewGuiLoiChuc(View):
    """Lưu lời chúc gửi qua form"""

    def post(self, request):
        """Nhận lời chúc gửi từ trang web"""

        form_data = FormWish(self.request.POST)
        data = {
            "is_valid": False,
        }
        if form_data.is_valid():
            form_data.save()
            data = {
                "is_valid": True,
            }
        return JsonResponse(data)

    def get(self, request):
        """Lấy csrf token"""
        token = get_token(request)
        return JsonResponse({"token": token})


class ViewTatCaLoiChuc(TemplateView):
    """Những lời chúc đã gửi"""

    template_name = "true_love/loi_chuc_da_gui.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if pk := kwargs.get("pk_id"):
            if wedding := Wedding.objects.select_related("chu_re", "co_dau").filter(
                id=pk
            ):
                wishes = Wish.objects.filter(wedding=wedding[0]).order_by("-created_at")
                context["wishes"] = wishes
        return context


class ViewTrueLoveInvitation(TemplateView):
    """Giao diện thiệp mời True love"""

    template_name = "true_love/true_love_invitation.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if uid := kwargs.get("uid"):
            if invitation := list(
                Invitation.objects.prefetch_related(
                    "nguoi_lien_quan__chu_re",
                    "nguoi_lien_quan__co_dau",
                ).filter(uid=uid)
            ):
                weddings = (
                    invitation[0].nguoi_lien_quan.chu_re.all()
                    or invitation[0].nguoi_lien_quan.co_dau.all()
                )
                ngay_to_chuc = weddings[0].ngay_to_chuc
                invitation_data = invitation[0]
                friend_pronoun, my_pronoun = invitation_data.cach_xung_ho.split("/")
                og_img_ratio = invitation_data.width_anh_goc / 256
                og_img_height = int(invitation_data.height_anh_goc / og_img_ratio)
                context["invitation_info"] = {
                    "ngay_to_chuc": ngay_to_chuc
                    if invitation_data.nguoi_lien_quan.gioi_tinh == "NAM"
                    else datetime.strptime("14-11-2023", "%d-%m-%Y").date(),
                    "ten": invitation_data.ten,
                    "facebook_id": invitation_data.facebook_id,
                    "resid": invitation_data.resid,
                    "authkey": invitation_data.authkey,
                    "width_anh_goc": invitation_data.width_anh_goc,
                    "og_img_width": 256,
                    "og_img_height": og_img_height,
                    "friend_pronoun": friend_pronoun,
                    "my_pronoun": my_pronoun,
                }
        return context

    def get(self, request, *args, **kwargs):
        template = super().get(self, request, *args, **kwargs)
        if "invitation_info" in template.context_data.keys():
            return template
        else:
            return HttpResponseRedirect(
                reverse(
                    "weddings:true_love_custom", kwargs={"slug": "tuan-anh-kim-oanh"}
                )
            )


class ViewCountDays(TemplateView):
    """Đếm ngày yêu nhau"""

    template_name = "love_story/count_days.html"

website/weddings/templates/true_love/coming-soon.html
{% load static %}
{% spaceless %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="html template">
    <meta name="keyword" content="your keyword goes to here">
    <meta name="author" content="themexriver">
    <title>True-Love-Bootstrap Wedding Template</title>
    <link href="{% static 'true_love/images/favicon.png' %}" rel="icon">
    <link href="{% static 'true_love/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,300' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Dancing+Script:700' rel='stylesheet' type='text/css'>
    <link href="{% static 'true_love/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'true_love/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'true_love/css/responsive.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <div class="site-loder">
        <div class="heart"></div>
    </div> <!-- end of site-loder -->

    <header id="home">
        <nav class="navbar" id="nav">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a class="navbar-brand" href="#">True <i class="fa fa-heart"></i> Love</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'weddings:true_love' %}">Home</a></li>
                        <li><a href="{% url 'weddings:true_love' %}#couple">Couple</a></li>
                        <li><a href="{% url 'weddings:true_love' %}#story">Story</a></li>
                        <li><a href="{% url 'weddings:true_love' %}#event">Events</a></li>
                        <li><a href="{% url 'weddings:true_love' %}#gallery">Gallery</a></li>
                        <li class="theme-logo hidden-xs">
                            <a href="{% url 'weddings:true_love' %}">
                              <img src="{% static 'true_love/images/logo.png' %}" alt="Logo" class="hidden-sm logo-rotating">
                              <img src="{% static 'true_love/images/logo-sm.png' %}" alt="Logo" class="hidden-md hidden-lg logo-rotating">
                                <div>
                                    <div>
                                        <span>True</span>
                                        <span>Love</span>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li><a href="{% url 'weddings:true_love' %}#people">People</a></li>
                        <li><a href="{% url 'weddings:true_love' %}#gift">Gift</a></li>
                        <li><a href="{% url 'weddings:true_love' %}#rsvp">RSVP</a></li>
                        <li class="dropdown">
                            <a href="#" role="button" aria-haspopup="true" aria-expanded="false">Blog <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="blog.html">Blog Style-1</a></li>
                                <li><a href="blog-2.html">Blog Style-2</a></li>
                                <li><a href="blog-details.html">Blog Details</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" role="button" aria-haspopup="true" aria-expanded="false">Pages <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="404.html">404 Page</a></li>
                                <li><a href="{% url 'weddings:coming_soon' %}">Coming Soon</a></li>
                                <li><a href="under-construction.html">Under Construction</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> <!-- end of nav -->
    </header>  <!-- end of header -->

    <section class="comming-soon-content section-padding">
        <div class="container">
            <h1>Coming soon</h1>
            <h2>We are coming soon</h2>
            <div class="row" id="clock">
                <div class="col col-md-10 col-md-offset-1">
                    <div class="col col-xs-3 col-sm-3 time">
                        <div class='days_dash' data-vp-add-class="visible bounceIn" data-vp-offset="0">
                            <div class="wrapper-digit">
                                <div class='digit'></div>
                                <div class='digit'></div>
                                <div class='digit'></div>
                                <p class='note dash_title'>Days</p>
                            </div>
                        </div>
                    </div>

                    <div class="col col-xs-3 col-sm-3 time">
                        <div class='hours_dash' data-vp-add-class="visible bounceIn" data-vp-offset="0">
                            <div class="wrapper-digit">
                                <div class='digit'></div>
                                <div class='digit'></div>
                                <p class='note dash_title'>Hours</p>
                            </div>
                        </div>
                    </div>

                    <div class="col col-xs-3 col-sm-3 time">
                        <div class='minutes_dash' data-vp-add-class="visible bounceIn" data-vp-offset="0">
                            <div class="wrapper-digit">
                                <div class=' digit'></div>
                                <div class=' digit'></div>
                                <p class='note dash_title'>Minutes</p>
                            </div>
                        </div>
                    </div>

                    <div class="col col-xs-3 col-sm-3 time">
                        <div class='seconds_dash' data-vp-add-class="visible bounceIn" data-vp-offset="0">
                            <div class="wrapper-digit">
                                <div class=' digit'></div>
                                <div class=' digit'></div>
                                <p class='note dash_title'>Seconds</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </section> <!-- end of blog-content -->

    <footer>
        <div class="row">
            <h2>Romeo &amp; Juleit</h2>
            <span class="date">24 April 2016 </span>
        </div>

        <div class="row">
            <div class="container">
                <div class="col col-sm-6">
                    <p>Copyright &copy; 2015 themexriver. All Rights Reserved</p>
                </div>
                <div class="col col-sm-6">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer> <!-- end of footer -->

    <script src="{% static 'true_love/js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'true_love/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'true_love/js/jquery.lwtCountdown-1.0.js' %}"></script>
    <script src="{% static 'true_love/js/coming-soon-script.js' %}"></script>
    <script src="{% static 'true_love/js/classie.js' %}"></script>
    <script src="{% static 'true_love/js/common-script.js' %}"></script>
</body>
</html>
{% endspaceless %}

website/weddings/templates/true_love/loi_chuc_da_gui.html
<div class="overlay"></div>
<div class="container">
  <div class="row section-heading">
    <div class="col col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
      <h2>Những lời chúc đã gửi</h2>
    </div>
  </div>
  <div class="row content">
    <div class="from-wrapper col col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
      <form class="form-inline">
        <div class="wish-box">
          {% for wish in wishes %}
          {% if forloop.counter0|divisibleby:2 %}
          <div class="wish-box-item ">
            <strong>{{ wish.name }}</strong>
            <p>{{ wish.message|safe|escapejs }}</p>
          </div>
          {% else %}
          <div class="wish-box-item bg">
            <strong>{{ wish.name }}</strong>
            <p>{{ wish.message|safe|escapejs }}</p>
          </div>
          {% endif %}
          {% endfor %}
        </div>
      </form>
    </div>
  </div>
  <!-- end of content -->
</div>

website/weddings/templates/true_love/true_love_invitation.html
{% load static %} {% spaceless %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta
      name="description"
      content="Ngày {{ invitation_info.ngay_to_chuc|date:'d-m-Y' }} trân trọng mời {{invitation_info.friend_pronoun}} {{ invitation_info.ten }} tới dự lễ cưới của {{ invitation_info.my_pronoun }}"
    />
    <meta
      name="keyword"
      content="Ngày {{ invitation_info.ngay_to_chuc|date:'d-m-Y' }} trân trọng mời {{invitation_info.friend_pronoun}} {{ invitation_info.ten }} tới dự lễ cưới của {{ invitation_info.my_pronoun }}"
    />
    <meta name="author" content="HuuTuanAnh" />

    <meta property="og:url" content="{{ request.build_absolute_uri }}{{ object.get_absolute_url }}" />
    <meta property="og:type" content="website" />
    <meta
      property="og:title"
      content="Trân trọng kính mời"
    />
    <meta
      property="og:description"
      content="Ngày {{ invitation_info.ngay_to_chuc|date:'d-m-Y' }} trân trọng kính mời {{invitation_info.friend_pronoun}} {{ invitation_info.ten }} tới dự lễ cưới của {{ invitation_info.my_pronoun }}"
    />
    <meta property="og:image" content="https://onedrive.live.com/embed?resid={{ invitation_info.resid }}&authkey={{ invitation_info.authkey }}&width={{ invitation_info.og_img_width}}&height={{ invitation_info.og_img_height }}" />
    <meta property="og:image:width" content="{{ invitation_info.og_img_width }}" />
    <meta property="og:image:height" content="{{ invitation_info.og_img_height }}" />
    <meta property="og:image:type" content="image/png" />
    <meta property="og:locale" content="vi_VN" />
    <link href="{% static 'true_love/css/invitation.css' %}" rel="stylesheet" />

    <title>
Ngày {{ invitation_info.ngay_to_chuc|date:'d-m-Y' }} trân trọng kính mời {{invitation_info.friend_pronoun}} {{ invitation_info.ten }} tới dự lễ cưới của {{ invitation_info.my_pronoun }}
    </title>
            <link href="{% static 'true_love/images/favicon.png' %}" rel="icon">
            <style type="text/css">
                @font-face {
                    font-family: "SVN-Vintage";
                    src: url({% static 'fonts/SVN-Vintage.otf' %}) format("opentype");
                }
                .box-text {
                    font-family: "SVN-Vintage", Verdana, Tahoma;
                }
            </style>
  </head>
  <body>
    <div id="container">
      <a href="{% url "weddings:true_love_custom" "tuan-anh-kim-oanh" %}" target="_blank" >
        <img
        src="https://onedrive.live.com/embed?resid={{ invitation_info.resid }}&authkey={{ invitation_info.authkey }}&width={{ invitation_info.width_anh_goc }}"
          alt="HuuTuanAnh"
        />
      </a>
      <div class="box-text">
        <h1>Lễ thành hôn</h1>
        <h1>Tuấn Anh ♥ Kim Oanh</h1>
        <p>Ngày {{ invitation_info.ngay_to_chuc|date:'d-m-Y' }}, trân trọng kính mời {{ invitation_info.friend_pronoun }} đến dự lễ thành hôn của vợ chồng {{ invitation_info.my_pronoun }}</p>
        <p>Rất hân hạnh được đón tiếp {{ invitation_info.friend_pronoun }}</p>
      </div>
    </div>
            <div class="donate-logo">
                <div class="donate-logo-secondary">
                    <div class="donate-logo-secondary-content">Xem lễ thành hôn của tôi</div>
                </div><a href="{% url "weddings:true_love_custom" "tuan-anh-kim-oanh" %}" class="buttonDonate">
                    <img src="{% static "true_love/images/donatebox.webp" %}"></a></div>
  </body>
</html>
{% endspaceless %}